# Eat Safe, Love

## Notebook Set Up

In [57]:
from pymongo import MongoClient
import pandas as pd
from pprint import pprint

In [58]:
# Create an instance of MongoClient
mongo = MongoClient(port=27017)

In [59]:
# assign the uk_food database to a variable name
db = mongo['uk_food']

In [60]:
# review the collections in our database
print(db.list_collection_names())

['establishments']

In [61]:
# assign the collection to a variable
establishments = db['establishments']

## Part 3: Exploratory Analysis
Unless otherwise stated, for each question: 
* Use `count_documents` to display the number of documents contained in the result.
* Display the first document in the results using `pprint`.
* Convert the result to a Pandas DataFrame, print the number of rows in the DataFrame, and display the first 10 rows.

### 1. Which establishments have a hygiene score equal to 20?

In [62]:
# Find the establishments with a hygiene score of 20
query = {'scores.Hygiene': 20}

# Use count_documents to display the number of documents in the result
establishments.count_documents(query)
good_hygiene = establishments.find_one(query)
# Display the first document in the results using pprint
print(f'There are {establishments.count_documents(query)} establishments with a hygiene score equal to 20')
pprint(good_hygiene)

There are 41 establishments with a hygiene score equal to 20
{'AddressLine1': '5-6 Southfields Road',
 'AddressLine2': 'Eastbourne',
 'AddressLine3': 'East Sussex',
 'AddressLine4': '',
 'BusinessName': 'The Chase Rest Home',
 'BusinessType': 'Caring Premises',
 'BusinessTypeID': 5,
 'ChangesByServerID': 0,
 'Distance': 4613.888288172291,
 'FHRSID': 110681,
 'LocalAuthorityBusinessID': '4029',
 'LocalAuthorityCode': '102',
 'LocalAuthorityEmailAddress': 'Customerfirst@eastbourne.gov.uk',
 'LocalAuthorityName': 'Eastbourne',
 'LocalAuthorityWebSite': 'http://www.eastbourne.gov.uk/foodratings',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'BN21 1BU',
 'RatingDate': '2021-09-23T00:00:00',
 'RatingKey': 'fhrs_0_en-gb',
 'RatingValue': 0,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('6715281d88908c6765d06cbb'),
 'geocode': {'latitude': Decimal128('50.7697050000000'),
             'longitude': Decimal128('0.276940000000000')},
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/110681',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 20, 'Hygiene': 20, 'Structural': 20}}

In [63]:
# Convert the result to a Pandas DataFrame
good_hygiene_df = pd.json_normalize(establishments.find(query))

# Display the number of rows in the DataFrame
good_hygiene_df.shape[0]

# Display the first 10 rows of the DataFrame
print(f'Number of rows: {good_hygiene_df.shape[0]}')
good_hygiene_df.head(10)

Number of rows: 41

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,geocode.longitude,geocode.latitude,meta.dataSource,meta.extractDate,meta.itemCount,meta.returncode,meta.totalCount,meta.totalPages,meta.pageSize,meta.pageNumber
0,6715281d88908c6765d06cbb,110681,0,4029,The Chase Rest Home,Caring Premises,5,5-6 Southfields Road,Eastbourne,East Sussex,...,0.276940000000000,50.7697050000000,None,0001-01-01T00:00:00,0,None,0,0,0,0
1,6715281d88908c6765d07040,612039,0,1970/FOOD,Brenalwood,Caring Premises,5,Hall Lane,Walton-on-the-Naze,Essex,...,1.27872100000000,51.8575360000000,None,0001-01-01T00:00:00,0,None,0,0,0,0
2,6715281d88908c6765d0734a,730933,0,1698/FOOD,Melrose Hotel,Hotel/bed & breakfast/guest house,7842,53 Marine Parade East,Clacton On Sea,Essex,...,1.15927000000000,51.7894290000000,None,0001-01-01T00:00:00,0,None,0,0,0,0
3,6715281d88908c6765d07537,172735,0,PI/000023858,Seaford Pizza,Takeaway/sandwich shop,7844,4 High Street,Seaford,East Sussex,...,0.102020000000000,50.7708850000000,None,0001-01-01T00:00:00,0,None,0,0,0,0
4,6715281d88908c6765d07549,172953,0,PI/000024532,Golden Palace,Restaurant/Cafe/Canteen,1,5 South Street,Seaford,East Sussex,...,0.101446000000000,50.7707240000000,None,0001-01-01T00:00:00,0,None,0,0,0,0
5,6715281d88908c6765d07ee5,512854,0,12/00816/BUTH,Ashby's Butchers,Retailers - other,4613,777 Southchurch Road,Southend-On-Sea,Essex,...,0.736349000000000,51.5414480000000,None,0001-01-01T00:00:00,0,None,0,0,0,0
6,6715281d88908c6765d08107,1537089,0,22/00224/RESTUN,South Sea Express Cuisine,Restaurant/Cafe/Canteen,1,33 Alexandra Street,Southend-on-sea,Essex,...,0.712167100000000,51.5350065000000,None,0001-01-01T00:00:00,0,None,0,0,0,0
7,6715281d88908c6765d09630,155648,0,EH/00006058,Golden Palace,Takeaway/sandwich shop,7844,7 London Road,Rayleigh,Essex,...,0.602364000000000,51.5915150000000,None,0001-01-01T00:00:00,0,None,0,0,0,0
8,6715281d88908c6765d09a72,1012883,0,17/00110/MIXED/S,The Tulip Tree,Restaurant/Cafe/Canteen,1,3 The Village,Chiddingstone,KENT,...,0.146449998021126,51.1859474182129,None,0001-01-01T00:00:00,0,None,0,0,0,0
9,6715281d88908c6765d0a288,644109,0,41811,F & S,Retailers - other,4613,,81 Southernhay,Basildon,...,0.462307000000000,51.5700500000000,None,0001-01-01T00:00:00,0,None,0,0,0,0

### 2. Which establishments in London have a `RatingValue` greater than or equal to 4?

In [64]:
# Find the establishments with London as the Local Authority and has a RatingValue greater than or equal to 4.
query = {
    'LocalAuthorityName': {'$regex': 'London', '$options': 'i'}, 
    'RatingValue': {'$gte': 4}
}

# Use count_documents to display the number of documents in the result
establishments.count_documents(query)

# Display the first document in the results using pprint
print(f'There are {establishments.count_documents(query)} establishments with a RatingValue >= 4')
pprint(establishments.find_one(query))

There are 33 establishments with a RatingValue >= 4
{'AddressLine1': 'Oak Apple Farm Building 103 Sheernes Docks',
 'AddressLine2': 'Sheppy Kent',
 'AddressLine3': '',
 'AddressLine4': '',
 'BusinessName': "Charlie's",
 'BusinessType': 'Other catering premises',
 'BusinessTypeID': 7841,
 'ChangesByServerID': 0,
 'Distance': 4627.439467780196,
 'FHRSID': 621707,
 'LocalAuthorityBusinessID': 'PI/000025307',
 'LocalAuthorityCode': '508',
 'LocalAuthorityEmailAddress': 'publicprotection@cityoflondon.gov.uk',
 'LocalAuthorityName': 'City of London Corporation',
 'LocalAuthorityWebSite': 'http://www.cityoflondon.gov.uk/Corporation/homepage.htm',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'ME12',
 'RatingDate': '2021-10-18T00:00:00',
 'RatingKey': 'fhrs_4_en-gb',
 'RatingValue': 4,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('6715281d88908c6765d086d4'),
 'geocode': {'latitude': Decimal128('51.3693210000000'),
             'longitude': Decimal128('0.508551000000000')},
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/621707',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 5, 'Hygiene': 5, 'Structural': 10}}

In [65]:
# Convert the result to a Pandas DataFrame
good_rating_df = pd.json_normalize(establishments.find(query))
# Display the number of rows in the DataFrame
good_rating_df.shape[0]
print(f'Number of rows: {good_rating_df.shape[0]}')
# Display the first 10 rows of the DataFrame
good_rating_df.head(10)

Number of rows: 33

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,geocode.longitude,geocode.latitude,meta.dataSource,meta.extractDate,meta.itemCount,meta.returncode,meta.totalCount,meta.totalPages,meta.pageSize,meta.pageNumber
0,6715281d88908c6765d086d4,621707,0,PI/000025307,Charlie's,Other catering premises,7841,Oak Apple Farm Building 103 Sheernes Docks,Sheppy Kent,,...,0.508551000000000,51.3693210000000,None,0001-01-01T00:00:00,0,None,0,0,0,0
1,6715281d88908c6765d08a00,1130836,0,PI/000034075,Mv City Cruises Erasmus,Other catering premises,7841,Cherry Garden Pier,Cherry Garden Street Rotherhithe,Charlton,...,0.249255999922752,51.1236228942871,None,0001-01-01T00:00:00,0,None,0,0,0,0
2,6715281d88908c6765d0954d,293783,0,PI/000002614,Benfleet Motor Yacht Club,Other catering premises,7841,Ferry Road,South Benfleet Essex,,...,0.561954000000000,51.5438310000000,None,0001-01-01T00:00:00,0,None,0,0,0,0
3,6715281d88908c6765d0a34c,1315095,0,PI/000036464,Coombs Catering t/a The Lock and Key,Restaurant/Cafe/Canteen,1,Leslie Ford House,Tilbury,Charlton,...,0.346336990594864,51.4640655517578,None,0001-01-01T00:00:00,0,None,0,0,0,0
4,6715281d88908c6765d0a34e,294474,0,PI/000014647,Tilbury Seafarers Centre,Restaurant/Cafe/Canteen,1,Tenants Row Tilbury Docks,Tilbury Essex,,...,0.346325000000000,51.4640780000000,None,0001-01-01T00:00:00,0,None,0,0,0,0
5,6715281d88908c6765d0aa54,294900,0,PI/000019066,Mv Valulla,Other catering premises,7841,Reeds River Cruises LtdKings ReachRiver Thames...,London,,...,0.287555000000000,51.5040710000000,None,0001-01-01T00:00:00,0,None,0,0,0,0
6,6715281e88908c6765d0cb5e,293756,0,PI/000002538,Tereza Joanne,Other catering premises,7841,Funcraft UK Ltd King George V Dock Woolwich Ma...,London,,...,0.0692860000000000,51.5011210000000,None,0001-01-01T00:00:00,0,None,0,0,0,0
7,6715281e88908c6765d0cf25,878523,0,PI/000029844,Brick Lane Brews,Restaurant/Cafe/Canteen,1,Air side London City Airport,London,,...,0.0480060000000000,51.5037330000000,None,0001-01-01T00:00:00,0,None,0,0,0,0
8,6715281e88908c6765d0cf44,294606,0,PI/000016185,WH Smith,Retailers - other,4613,London City Airport,Silvertown London,,...,0.0479655750095844,51.5041122436523,None,0001-01-01T00:00:00,0,None,0,0,0,0
9,6715281e88908c6765d0cf46,293772,0,PI/000002585,The Nuance Group (UK) Limited,Retailers - other,4613,Duty Free Shop Passenger Terminal,London City AirportRoyal DocksLondon,,...,0.0479660000000000,51.5041120000000,None,0001-01-01T00:00:00,0,None,0,0,0,0

### 3. What are the top 5 establishments with a `RatingValue` rating value of 5, sorted by lowest hygiene score, nearest to the new restaurant added, "Penang Flavours"?

In [66]:
# Search within 0.01 degree on either side of the latitude and longitude.
# Rating value must equal 5
# Sort by hygiene score

degree_search = 0.01
latitude = 51.49014200
longitude = 0.08384000

query = {
    'RatingValue' : 5,
    'geocode.latitude': {'$gte': latitude - degree_search, '$lte': latitude + degree_search},
    'geocode.longitude': {'$gte': longitude - degree_search, '$lte': longitude + degree_search}
}

sort = [('scores.Hygiene', -1)]
limit = 5

# Print the results
pprint(list(establishments.find(query).sort(sort).limit(limit)))

[{'AddressLine1': '101 Plumstead High Street',
  'AddressLine2': '',
  'AddressLine3': 'Plumstead',
  'AddressLine4': 'Greenwich',
  'BusinessName': 'Lucky Food & Wine',
  'BusinessType': 'Retailers - other',
  'BusinessTypeID': 4613,
  'ChangesByServerID': 0,
  'Distance': 4647.024793263386,
  'FHRSID': 695287,
  'LocalAuthorityBusinessID': 'PI/000182135',
  'LocalAuthorityCode': '511',
  'LocalAuthorityEmailAddress': 'health@royalgreenwich.gov.uk',
  'LocalAuthorityName': 'Greenwich',
  'LocalAuthorityWebSite': 'http://www.royalgreenwich.gov.uk',
  'NewRatingPending': False,
  'Phone': '',
  'PostCode': 'SE18 1SB',
  'RatingDate': '2022-06-25T00:00:00',
  'RatingKey': 'fhrs_5_en-gb',
  'RatingValue': 5,
  'RightToReply': '',
  'SchemeType': 'FHRS',
  '_id': ObjectId('6715281e88908c6765d0c5bd'),
  'geocode': {'latitude': Decimal128('51.4878934000000'),
              'longitude': Decimal128('0.0910104000000000')},
  'links': [{'href': 'http://api.ratings.food.gov.uk/establishments/695287',
             'rel': 'self'}],
  'meta': {'dataSource': None,
           'extractDate': '0001-01-01T00:00:00',
           'itemCount': 0,
           'pageNumber': 0,
           'pageSize': 0,
           'returncode': None,
           'totalCount': 0,
           'totalPages': 0},
  'scores': {'ConfidenceInManagement': 5, 'Hygiene': 5, 'Structural': 5}},
 {'AddressLine1': '112 Plumstead High Street',
  'AddressLine2': '',
  'AddressLine3': 'Plumstead',
  'AddressLine4': 'Greenwich',
  'BusinessName': 'Fineway Cash & Carry',
  'BusinessType': 'Retailers - other',
  'BusinessTypeID': 4613,
  'ChangesByServerID': 0,
  'Distance': 4647.016995291011,
  'FHRSID': 694606,
  'LocalAuthorityBusinessID': 'PI/000116584',
  'LocalAuthorityCode': '511',
  'LocalAuthorityEmailAddress': 'health@royalgreenwich.gov.uk',
  'LocalAuthorityName': 'Greenwich',
  'LocalAuthorityWebSite': 'http://www.royalgreenwich.gov.uk',
  'NewRatingPending': False,
  'Phone': '',
  'PostCode': 'SE18 1SJ',
  'RatingDate': '2020-10-20T00:00:00',
  'RatingKey': 'fhrs_5_en-gb',
  'RatingValue': 5,
  'RightToReply': '',
  'SchemeType': 'FHRS',
  '_id': ObjectId('6715281e88908c6765d0c5aa'),
  'geocode': {'latitude': Decimal128('51.4876089000000'),
              'longitude': Decimal128('0.0909382000000000')},
  'links': [{'href': 'http://api.ratings.food.gov.uk/establishments/694606',
             'rel': 'self'}],
  'meta': {'dataSource': None,
           'extractDate': '0001-01-01T00:00:00',
           'itemCount': 0,
           'pageNumber': 0,
           'pageSize': 0,
           'returncode': None,
           'totalCount': 0,
           'totalPages': 0},
  'scores': {'ConfidenceInManagement': 5, 'Hygiene': 5, 'Structural': 5}},
 {'AddressLine1': '104 Plumstead High Street',
  'AddressLine2': '',
  'AddressLine3': 'Plumstead',
  'AddressLine4': 'Greenwich',
  'BusinessName': 'Everest Stores Ltd',
  'BusinessType': 'Retailers - other',
  'BusinessTypeID': 4613,
  'ChangesByServerID': 0,
  'Distance': 4647.041728368117,
  'FHRSID': 695033,
  'LocalAuthorityBusinessID': 'PI/000172986',
  'LocalAuthorityCode': '511',
  'LocalAuthorityEmailAddress': 'health@royalgreenwich.gov.uk',
  'LocalAuthorityName': 'Greenwich',
  'LocalAuthorityWebSite': 'http://www.royalgreenwich.gov.uk',
  'NewRatingPending': False,
  'Phone': '',
  'PostCode': 'SE18 1SJ',
  'RatingDate': '2021-09-13T00:00:00',
  'RatingKey': 'fhrs_5_en-gb',
  'RatingValue': 5,
  'RightToReply': '',
  'SchemeType': 'FHRS',
  '_id': ObjectId('6715281e88908c6765d0c5df'),
  'geocode': {'latitude': Decimal128('51.4876718000000'),
              'longitude': Decimal128('0.0903232000000000')},
  'links': [{'href': 'http://api.ratings.food.gov.uk/establishments/695033',
             'rel': 'self'}],
  'meta': {'dataSource': None,
           'extractDate': '0001-01-01T00:00:00',
           'itemCount': 0,
           'pageNumber': 0,
           'pageSize': 0,
           'returncode': None,
           'totalCount': 0,
           'totalPages': 0},
  'scores': {'ConfidenceInManagement': 5, 'Hygiene': 5, 'Structural': 5}},
 {'AddressLine1': '102 Plumstead High Street',
  'AddressLine2': '',
  'AddressLine3': 'Plumstead',
  'AddressLine4': 'Greenwich',
  'BusinessName': 'Premier Express',
  'BusinessType': 'Retailers - other',
  'BusinessTypeID': 4613,
  'ChangesByServerID': 0,
  'Distance': 4647.038806595731,
  'FHRSID': 695566,
  'LocalAuthorityBusinessID': 'PI/000188497',
  'LocalAuthorityCode': '511',
  'LocalAuthorityEmailAddress': 'health@royalgreenwich.gov.uk',
  'LocalAuthorityName': 'Greenwich',
  'LocalAuthorityWebSite': 'http://www.royalgreenwich.gov.uk',
  'NewRatingPending': False,
  'Phone': '',
  'PostCode': 'SE18 1SJ',
  'RatingDate': '2021-06-10T00:00:00',
  'RatingKey': 'fhrs_5_en-gb',
  'RatingValue': 5,
  'RightToReply': '',
  'SchemeType': 'FHRS',
  '_id': ObjectId('6715281e88908c6765d0c5d9'),
  'geocode': {'latitude': Decimal128('51.4877234000000'),
              'longitude': Decimal128('0.0904552000000000')},
  'links': [{'href': 'http://api.ratings.food.gov.uk/establishments/695566',
             'rel': 'self'}],
  'meta': {'dataSource': None,
           'extractDate': '0001-01-01T00:00:00',
           'itemCount': 0,
           'pageNumber': 0,
           'pageSize': 0,
           'returncode': None,
           'totalCount': 0,
           'totalPages': 0},
  'scores': {'ConfidenceInManagement': 0, 'Hygiene': 5, 'Structural': 0}},
 {'AddressLine1': '152 Plumstead High Street',
  'AddressLine2': '',
  'AddressLine3': 'Plumstead',
  'AddressLine4': 'Greenwich',
  'BusinessName': 'TIWA N TIWA African Restaurant Ltd',
  'BusinessType': 'Restaurant/Cafe/Canteen',
  'BusinessTypeID': 1,
  'ChangesByServerID': 0,
  'Distance': 4646.930146257832,
  'FHRSID': 1069652,
  'LocalAuthorityBusinessID': 'PI/000206841',
  'LocalAuthorityCode': '511',
  'LocalAuthorityEmailAddress': 'health@royalgreenwich.gov.uk',
  'LocalAuthorityName': 'Greenwich',
  'LocalAuthorityWebSite': 'http://www.royalgreenwich.gov.uk',
  'NewRatingPending': False,
  'Phone': '',
  'PostCode': 'SE18 1JQ',
  'RatingDate': '2020-10-24T00:00:00',
  'RatingKey': 'fhrs_5_en-gb',
  'RatingValue': 5,
  'RightToReply': '',
  'SchemeType': 'FHRS',
  '_id': ObjectId('6715281e88908c6765d0c4cc'),
  'geocode': {'latitude': Decimal128('51.4870351000000'),
              'longitude': Decimal128('0.0927429000000000')},
  'links': [{'href': 'http://api.ratings.food.gov.uk/establishments/1069652',
             'rel': 'self'}],
  'meta': {'dataSource': None,
           'extractDate': '0001-01-01T00:00:00',
           'itemCount': 0,
           'pageNumber': 0,
           'pageSize': 0,
           'returncode': None,
           'totalCount': 0,
           'totalPages': 0},
  'scores': {'ConfidenceInManagement': 5, 'Hygiene': 5, 'Structural': 5}}]

In [67]:
# Convert result to Pandas DataFrame
top5 = pd.json_normalize(establishments.find(query).sort(sort).limit(limit))
top5

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,geocode.longitude,geocode.latitude,meta.dataSource,meta.extractDate,meta.itemCount,meta.returncode,meta.totalCount,meta.totalPages,meta.pageSize,meta.pageNumber
0,6715281e88908c6765d0c5bd,695287,0,PI/000182135,Lucky Food & Wine,Retailers - other,4613,101 Plumstead High Street,,Plumstead,...,0.0910104000000000,51.4878934000000,None,0001-01-01T00:00:00,0,None,0,0,0,0
1,6715281e88908c6765d0c5aa,694606,0,PI/000116584,Fineway Cash & Carry,Retailers - other,4613,112 Plumstead High Street,,Plumstead,...,0.0909382000000000,51.4876089000000,None,0001-01-01T00:00:00,0,None,0,0,0,0
2,6715281e88908c6765d0c5df,695033,0,PI/000172986,Everest Stores Ltd,Retailers - other,4613,104 Plumstead High Street,,Plumstead,...,0.0903232000000000,51.4876718000000,None,0001-01-01T00:00:00,0,None,0,0,0,0
3,6715281e88908c6765d0c5d9,695566,0,PI/000188497,Premier Express,Retailers - other,4613,102 Plumstead High Street,,Plumstead,...,0.0904552000000000,51.4877234000000,None,0001-01-01T00:00:00,0,None,0,0,0,0
4,6715281e88908c6765d0c4cc,1069652,0,PI/000206841,TIWA N TIWA African Restaurant Ltd,Restaurant/Cafe/Canteen,1,152 Plumstead High Street,,Plumstead,...,0.0927429000000000,51.4870351000000,None,0001-01-01T00:00:00,0,None,0,0,0,0

### 4. How many establishments in each Local Authority area have a hygiene score of 0?

In [68]:
# Create a pipeline that:
# 1. Matches establishments with a hygiene score of 0
match_query = {'$match': {'scores.Hygiene': 0}}

# 2. Groups the matches by Local Authority
group_query = {'$group': {'_id': "$LocalAuthorityName", 'count': { '$sum': 1 }}}

# 3. Sorts the matches from highest to lowest
sort_values = {'$sort': { 'count': -1 }}
limit = 10

pipeline = [match_query, group_query, sort_values]

# Print the number of documents in the result
# print(establishments.count_documents(pipeline))

# Print the first 10 results
results = list(establishments.aggregate(pipeline))
print(len(results))

pprint(results[0:10])

55
[{'_id': 'Thanet', 'count': 1130},
 {'_id': 'Greenwich', 'count': 882},
 {'_id': 'Maidstone', 'count': 713},
 {'_id': 'Newham', 'count': 711},
 {'_id': 'Swale', 'count': 686},
 {'_id': 'Chelmsford', 'count': 680},
 {'_id': 'Medway', 'count': 672},
 {'_id': 'Bexley', 'count': 607},
 {'_id': 'Southend-On-Sea', 'count': 586},
 {'_id': 'Tendring', 'count': 542}]

In [69]:
# Convert the result to a Pandas DataFrame
local_authority_good = pd.json_normalize(results)

# Display the number of rows in the DataFrame
local_authority_good.shape[0]

print(f'Number of rows: {local_authority_good.shape[0]}')
# Display the first 10 rows of the DataFrame
local_authority_good.head(10)

Number of rows: 55

               _id  count
0           Thanet   1130
1        Greenwich    882
2        Maidstone    713
3           Newham    711
4            Swale    686
5       Chelmsford    680
6           Medway    672
7           Bexley    607
8  Southend-On-Sea    586
9         Tendring    542